### ISSUE TITLE
Для UnderlinedTextField/UnderlinedTextView пересчитывать высоту всей view если подсказка есть, но ее не видно

### ISSUE THREAD

**Issue by Alelenka** [chausovSurfStudio/TextFieldsCatalog#105]
![изображение](https://user-images.githubusercontent.com/4083274/102859534-1c189900-443d-11eb-8cd7-56ad90b849a8.png)

Сейчас если задать `hint` то высота UnderlinedTextField/UnderlinedTextView не будет меняться когда подсказка не видна, возможно это стоит поправить.

Если так и задумывалось и это не баг, а фича - то issue стоит удалить :)

**Comment by chausovSurfStudio** [comment]
давай более полное описание)
какая политика `HeightLayoutPolicy` установлена, и сам кейс пошагово - когда высота должна изменяться, но не изменяется

**Comment by Alelenka** [comment]
Неактуально, проблема была в неверных констрейнтах - так UILable подсказки/ошибки не должен иметь bottomConstraint к superview и тогда проблемы не будет
