### ISSUE TITLE
[BUG] TextView прыгает каретка/поле проскраливается за верхнюю границу View при переходе на новую строку (ios11.4)

### ISSUE THREAD

**Issue by Alelenka** [chausovSurfStudio/TextFieldsCatalog#111]
**Describe the bug**
При использовании UnderlinedTextView и его наследников при переходе на новую строку, первый раз и иногда 3 - каретка прыгает и возвращается визуально на первую предыдущую строку, по факту -TextView  проскроливается и первая строка оказывается за пределами видимости, скорее всего из-за ошибки расчета высоты, но надо покопать, до версии 0.14. такое поведение можно было поймать если не указать у поля heightPolicy
На ios 12 и выше такой проблемы не выявлено

**To Reproduce**

1. Открыть примеры полей
2. Симулятор 5s с ios 11.4
3. Перейти на UITextView с подчеркиванием
4. нажать return несколько раз, можно с текстом или без

**Expected behavior**
Как и на версиях ios >= 12 поле не скролится, а только увеличивается по высоте

**Library version and device type**
 - iOS version: 11.4
 - device type: iPhone 5s

**Comment by chausovSurfStudio** [comment]
Поправлено в рамках https://github.com/chausovSurfStudio/TextFieldsCatalog/pull/123, будет в версии 0.17.0
