### ISSUE TITLE
Метод setup(heightConstraint:) пропал в версии 0.14.0

### ISSUE THREAD

**Issue by quazarteam** [chausovSurfStudio/TextFieldsCatalog#114]
Добрый день,

Использовали версию 0.12.3 в которой был метод UnderlineTextField.setup(heightConstraint:) который устанавливал высоту, заданную в XIB через NSLayoutConstraint.

    textField.setup(heightConstraint: containerHeightConstraint)
    textField.heightLayoutPolicy = .elastic(minHeight: 60, bottomSpace: 5, ignoreEmptyHint: true)

После обновления до версии 0.14.0 данный метод пропал и в документации нет указания чем его заменить. Каким образом теперь устанавливать высоту текстфилда через констрейнты?

Заранее спасибо за информацию.

**Comment by chausovSurfStudio** [comment]
Добрый день!
Да, вы правы, на документацию стало уходить слишком много времени, сейчас рассматриваем способы отказа от такой подробной документации (к примеру, начать более подробно комментировать код, тем самым обогащая автоматически генерируемую документацию, а в общей документации указывать только вот такие каверзные моменты). Поэтому она не всегда может совпадать с действительностью (если речь идет о последних изменениях, но их вроде не сильно много). По данному вопросу - да, упустили(

Изменения произошли в версии 0.14.0, вы правы. [Краткое содержание](https://github.com/chausovSurfStudio/TextFieldsCatalog/releases/tag/0.14.0) изменений - здесь можно посмотреть что надо сделать для миграции. Ну или если более подробно и с примерами - то вам [сюда](https://github.com/chausovSurfStudio/TextFieldsCatalog/pull/108), можно в данном пул-реквесте посмотреть на изменения в Example-проекте - вот примерно то же самое сделать нужно (тут лучше обратить внимание на `ExamplesViewController.xib`)

Фактически, что надо сделать (вариант с версткой из ксибы):
* убрать констрейнт на высоту для поля ввода
* xcode начинает ругаться на вас, что ему непонятно, какая высота должна быть у поля
* выставляете ему intrisicSize == placeholder
![Снимок экрана 2021-04-25 в 19 12 20](https://user-images.githubusercontent.com/8776643/116000767-36849e00-a5fa-11eb-9cd9-bc701446ff25.png)

Если еще остались вопросы - буду рад помочь)
