### ISSUE TITLE
Поведение подчеркивающей линии при добавлении на кастомное superview

### ISSUE THREAD

**Issue by chausovSurfStudio** [chausovSurfStudio/TextFieldsCatalog#44]
Был вот такой вот PR - https://github.com/chausovSurfStudio/TextFieldsCatalog/pull/40.
В нем стало возможно добавить линию, подчеркивающую поле ввода, не к другим элементам на superview, как обычно, а на какое-либо свое.

Было замечено, что отступы, которые можно задать там же в параметрах конфигурации, не всегда при этом отрабатывают корректно, если ширина передаваемого superview отличается от ширины самого поля (к примеру, мы хотим отступ справа/слева в 5pt, но линия может вылезать справа за пределы передаваемого superview).

Необходимо:

- проверить, так ли это
- если баг есть - найти причину и поправить
- посмотреть реализацию UnderlinedTextVIew, там кажется отступы, задаваемые пользователем, вообще никак в расчетах не участвуют, можно было бы и добавить
- обновить документацию

**Comment by fixique** [comment]
Баг не подтвердился

**Comment by chausovSurfStudio** [comment]
хотя нет, третий и четвертый пункты остались

**Comment by chausovSurfStudio** [comment]
Поправилось в процессе внутреннего рефакторинга, видимо, ибо сейчас проблемы не обнаружено, да и на реальных проектах вроде норм было.
Да и по коду вроде норм, учитывается передаваемое superview.
