### ISSUE TITLE
Использование полей ввода в отдельных модулях

### ISSUE THREAD

**Issue by chausovSurfStudio** [chausovSurfStudio/TextFieldsCatalog#45]
Если ваше приложение построено по принципу многомодульной архитектуры - то при затягивании туда полей ввода и сборке этого модуля будут выскакивать 6 ворнингов. Надо бы понять причину их появления и пофиксить

**Comment by chausovSurfStudio** [comment]
![Снимок экрана 2019-09-26 в 9 20 57](https://user-images.githubusercontent.com/8776643/65663357-35b31100-e03f-11e9-9376-7fafcc161d75.png)
а это пример такого ворнинга

**Comment by fixique** [comment]
Не удалось воспроизвести на Xcode11

**Comment by chausovSurfStudio** [comment]
закрыто за давностью (да вроде и не воспроизводилось более)
