### ISSUE TITLE
Добавить SPM

### ISSUE THREAD

**Issue by fixique** [chausovSurfStudio/TextFieldsCatalog#49]
Необходимо добавить возможность затягивать либу через Swift Package Manager и проверить как-это будет работать в модульном приложение.

**Comment by chausovSurfStudio** [comment]
реализовано, доступно в версии https://github.com/chausovSurfStudio/TextFieldsCatalog/releases/tag/0.13.0

**Comment by chausovSurfStudio** [comment]
реализовано, доступно в версии https://github.com/chausovSurfStudio/TextFieldsCatalog/releases/tag/0.13.0
