### ISSUE TITLE
Добавить возможность выбора разных шрифтов для плавающего placeholder

### ISSUE THREAD

**Issue by drxlx** [chausovSurfStudio/TextFieldsCatalog#67]
Сейчас судя по конфигурации можно выбрать только общий шрифт и разные размеры для него, хотелось бы видеть разные шрифты для обоих состояний.

**Comment by chausovSurfStudio** [comment]
В будущем апдейте - появится возможность реализовать собственный сервис, который бы отвечал за отрисовку плейсхолдера, и вот там уже можно будет самому поупражняться и сделать такой плейсхолдер, у которого бы менялся не только кегль, но и сам тип)

**Comment by chausovSurfStudio** [comment]
вместе с релизом 0.11.0 появилась возможность самому писать реализацию для плейсхолдера -> в том числе и такую, где будет возможность выбора разных шрифтов)
